[[headers]]
	for = "/*"
	[headers.values]
		# Require use of HTTPS on the website
		Strict-Transport-Security = "max-age=63072000"

		# Request the referer not to be sent when navigating from wiki.rustfu.rs
		# This is to protect user privacy; we could use `same-origin` but we aren't
		#  keeping track of referrers anyhow.
		Referrer-Policy = "no-referrer"

		# Prevent browsers from incorrectly detecting non-scripts as scripts
		X-Content-Type-Options = "nosniff"

		# Block site from being framed with X-Frame-Options and CSP
		Content-Security-Policy = "frame-ancestors 'none'"
		X-Frame-Options = "DENY"

		# Block pages from loading when they detect reflected XSS attacks
		X-XSS-Protection = "1; mode=block"
